name: boitex_info
description: Boitex-Info app
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  google_fonts: ^6.2.1
  http: ^1.2.1
  crypto: ^3.0.3
  intl: ^0.20.2
  pdf: ^3.11.3
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  printing: ^5.14.0
  signature: ^5.5.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fl_chart: ^0.68.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.2.1
  onesignal_flutter: ^5.2.1
  async: ^2.11.0
  flutter_riverpod: ^2.5.1
  timeago: ^3.6.1
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  # --- MODIFIED: Upgraded the version to resolve the conflict ---
  syncfusion_flutter_gauges: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/images/boitex_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/boitex_logo.png"
  min_sdk_android: 21