// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDA_7XPKYeDJTqEnicFruWioQej8nFb4',
    appId: '1:1043072149264:web:0977cfa874f52e73222795',
    messagingSenderId: '1043072149264',
    projectId: 'boitexinfo-5fc66',
    authDomain: 'boitexinfo-5fc66.firebaseapp.com',
    storageBucket: 'boitexinfo-5fc66.firebasestorage.app',
    measurementId: 'G-N1S3R38QDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpd2t2B8mU4wrRAPP8Zne5tGM8jAcj_9k',
    appId: '1:1043072149264:android:ff0178131e1fc3d3222795',
    messagingSenderId: '1043072149264',
    projectId: 'boitexinfo-5fc66',
    storageBucket: 'boitexinfo-5fc66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdz9NN37gr13GkX1twZpj5xeDF_8w1PJ8',
    appId: '1:1043072149264:ios:362d9045ce7fb0c5222795',
    messagingSenderId: '1043072149264',
    projectId: 'boitexinfo-5fc66',
    storageBucket: 'boitexinfo-5fc66.firebasestorage.app',
    iosBundleId: 'com.example.boitexInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdz9NN37gr13GkX1twZpj5xeDF_8w1PJ8',
    appId: '1:1043072149264:ios:362d9045ce7fb0c5222795',
    messagingSenderId: '1043072149264',
    projectId: 'boitexinfo-5fc66',
    storageBucket: 'boitexinfo-5fc66.firebasestorage.app',
    iosBundleId: 'com.example.boitexInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNDA_7XPKYeDJTqEnicFruWioQej8nFb4',
    appId: '1:1043072149264:web:cbefb4a2c69eff63222795',
    messagingSenderId: '1043072149264',
    projectId: 'boitexinfo-5fc66',
    authDomain: 'boitexinfo-5fc66.firebaseapp.com',
    storageBucket: 'boitexinfo-5fc66.firebasestorage.app',
    measurementId: 'G-NJMN9SDHSN',
  );
}
